name: Deploy

on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: python -m pip install --upgrade pipenv && pipenv install
      - name: Clone
        env:
          EVENTS: "${{ toJson(github.event.client_payload) }}"
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
          AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
        run: pipenv run python deploy.py && echo "PROJECT_ID=$(cat project_id)" >> $GITHUB_ENV
      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ env.PROJECT_ID }}
          working-directory: ./vercel
